import { GetServerSideProps, InferGetServerSidePropsType } from 'next'
import Head from 'next/head';
import Markdown from '../../components/Markdown';
import Navbar from '../../components/Navbar';
import { trpc } from '../../utils/trpc'

const SinglePost = ({id}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
    const {data} = trpc.useQuery(["post.get-post-by-id", {id}]);

    
  return (
    <>  
     <Head>
        <title>{data?.seoTitle || "Blogger"}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
            <main className='max-w-6xl w-full mx-auto pt-10 flex flex-col items-center'>
            <h1 className='text-center text-6xl pb-10'>{data?.title}</h1>
            <Markdown>{data?.content as string}</Markdown>  
        </main>
    </>
  )
}

export default SinglePost

export const getServerSideProps: GetServerSideProps = async({query})=> {
const {id} = query

    return {
        props: {
            id
        }
    }
}